version: 0.2
env:
   AWS_region      : /project1/aws-region
   ECR_REPO_URL    : /project1/ECR_REPO_URL
   EKS_CLUSTER_NAME: /project1/EKS_CLUSTER_NAME

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo "Logging in to ECR at $ECR_REPO_URL"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URL
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO_URL:latest .
      - docker push $ECR_REPO_URL:latest
  post_build:
    commands:
      - echo Deploying to EKS...
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - sed "s|<REPLACE_WITH_IMAGE>|$ECR_REPO_URL:latest|g" k8s/deployment.yaml | kubectl apply -f -
      - kubectl apply -f k8s/service.yaml
